# fetch a specific nixpkgs revision as a package stored in the nix store
# referenced under an output hash to have faster evaluations and allow keeping
# it alive when garbage collecting as a package dependency.
let
    # so that we can use `runCommand`
    bootStrap = import <nixpkgs> {};
    # the revision of the nixpkgs repo we are pegging to
    rev = "62de360d75419386b69ea4af4a8ce104949a8242";
    # hash generated by doing nix-prefetch-url --unpack https://github.com/NixOS/nixpkgs-channels/archive/{rev}.tar.gz
    hash = "1iincgcgswg29znpn3whpa04c1waj6ihn38db5v330laa0hdjhxp";
    src = builtins.fetchTarball
    {
      name = "nixpkgs-tarball-${rev}";
      url = "https://github.com/NixOS/nixpkgs/archive/${rev}.tar.gz";
      sha256 = hash;
    };
in
   bootStrap.runCommand "nixpkgs-${rev}" {
    outputHashMode = "recursive";
    outputHashAlgo = "sha256";
    outputHash = hash;
    inherit src;
  }
  ''
  cp -r $src $out
  ''
